### ISSUE TITLE
Research possibility to conduct our Thai tokenizer

### ISSUE THREAD

**Issue by kwankoravich** [OpenThaiGPT/openthaigpt-pretraining#125]
Research the possibility to conduct the model of Thai tokenizer by considering model architecture, data sourcing

**Comment by jingwora** [comment]
I will work on this.

**Comment by jingwora** [comment]
Please find summary of my research:
1. Syllable tokenizer shows good result in variouse senario. It should be an candidate for tokenizer test.
2. From many tokenization papers (eq. WANGCHANBERTA), we can evaluated variouse  tokenizer to find the best one.
