### ISSUE TITLE
Crawl and clean PRD data

### ISSUE THREAD

**Issue by Chawak** [OpenThaiGPT/openthaigpt-pretraining#140]
src:https://www.prd.go.th/th/page/item/index/id/1#

**Comment by nakarin** [comment]
Completed.
You can load from HF dataset at https://huggingface.co/datasets/nakcnx/prd_news.

**Comment by Chawak** [comment]
Is there anything to clean in the dataset krub P'Name ? If there isn't, this issue can be closed.

**Comment by nakarin** [comment]
Nothing to clean krub.
