### ISSUE TITLE
EDA other public corpus

### ISSUE THREAD

**Issue by new5558** [OpenThaiGPT/openthaigpt-pretraining#16]
(Not first priority)

Description : EDA +clean other public source than OSCAR, cc100, mC4

![Image](https://user-images.githubusercontent.com/12471844/226094866-d84d8c47-4935-4590-b5c8-574388b78d9b.png)

Other dataset :
Data Set Thai law: https://github.com/PyThaiNLP/thai-law
Ratchagitcha Corpus: https://github.com/narze/ratchagitja.md

**Comment by ArthurMinovsky** [comment]
กลอน Corpus: https://github.com/korakot/sunthorn

**Comment by Chawak** [comment]
Thai Law => Cleaned => Just load and use

**Comment by nen108** [comment]
เพลง Corpus => ภาษาท้องถิ่น Corpus
