### ISSUE TITLE
Research Thai Government corpus

### ISSUE THREAD

**Issue by new5558** [OpenThaiGPT/openthaigpt-pretraining#17]
![Image](https://user-images.githubusercontent.com/12471844/226099624-8f3b7f29-366b-4d90-8cd0-f0ce7a60e26e.png)

**Comment by i17bkk** [comment]
![Screen Shot 2566-03-25 at 21 49 37](https://user-images.githubusercontent.com/9200876/227724624-1f4b317d-66ff-42e6-ba57-f68fce3abfe6.png)
![Screen Shot 2566-03-25 at 21 50 11](https://user-images.githubusercontent.com/9200876/227724681-b94b3ca1-6a64-4f1f-a37b-f10d1d3ced62.png)
ไฟล์ส่วนใหญ่จะเป็น CSV file กับ Excel ไฟล์  คงต้องใช้แรงงานจำนวนมากเข้าไป กำหนดว่าจะเอาข้อมูล Column ไหน ค่าไหนบ้างนะครับ  ส่วน Meta data ของข้อมูลทำไว้แล้วคงต้องเลือกเอาที่เราจะใช้ แล้วแยกออกเป็น text file อีกตัวประกบกับ CSV   โปรแกรมอาจเขียน Rust อ่าน CSV file + text file เข้าไปใส่ตอน Train   ส่วน EDA คงไม่ต้องทำมาก เนื่องจากเป็นข้อมูลราชการ   ผมดูข้อมูลคร่าวๆ ช่วยแนะนำด้วยนะครับ ขอบคุณครับ

**Comment by kandation** [comment]
ไปเจอ Dataset เอกสารราชการที่มีคุณ Chomtana Crawl มาเก็บไว้แล้ว แต่ข้อเสียคือ เป็น pdf และเป็นรูปภาพด้วย อาจจะต้องทำ OCR 
https://www.kaggle.com/datasets/chomtana/thai-ocr-dla-document

ส่วนเอกสารที่เป็นเอกสารประกาศโรงเรียน ( Scorpe: โรงเรียนมัธยม) ก็มีบางส่วนที่เป็น Pdf-Text บางส่วนก็เป็น Pdf-Img แต่ความยากคือ หน้าเว็บแต่ละโรงเรียนแทบจะต่างกันมาก ๆ จะเขียน script crawl อาจจะต้องเขียนโรงเรียนต่อโรงเรียนเลย และเท่าที่ EDA ดูมาด้วยต่า ก็จะประกอบไปด้วย เนื้อประกาศ แล้วก็ บางครั้งก็มีตารางรายชื่อคนจำนวนมาก

ส่วนประกาศทางมหาวิทยาลัย บางที่ก็เป็น pdf บางที่ก็แปะเป็นภาพ ในหน้า content

ส่วน OPEN DATA GOV โดยมากจะเป็น csv ที่เป็นตัวเลขสถิติเลย บริบทพวกที่เป็นประกาศ หรืออื่นๆ มีน้อย ทั้งนี้ เราอาจจะตามลิงก์ต้นทางไปที่เว็บไซต์แล้ว crawnl เอาประกาศมาได้ (เช่นกับข้างต้น อาจจะเป็นประกาศ PDF-IMG)

ถ้ามองในเรื่องจะทำ ocr ไฟล์ส่วนใหญ่เป็น pdf-img ซึ่งสามารถแบ่งเป็น clean-scan  คือ ไฟล์ที่สแกนมาตรง สะอาด ไม่มีพื้นหลังหรือลายน้ำ สามารถทำ ocr ได้ง่าย, กับ defect-scan เช่นลายดำ เอียง หรืออักษรไม่ชัด หรือ scan ซ้ำแล้วซ้ำอีก 

แหล่งข้อมูลอื่นๆ 
https://dataportal.asia/dataset?vocab_economy_names=Thailand&res_format=PDF

**Comment by ArthurMinovsky** [comment]
Next Step: Find a solution to rearrange characters for correcting text that scrapes from PDF.
