### ISSUE TITLE
[Super AI] Research English corpus

### ISSUE THREAD

**Issue by new5558** [OpenThaiGPT/openthaigpt-pretraining#18]
Possible candidates
- C4
- CC100 English
- OSCAR English
- The Pile: https://arxiv.org/abs/2101.00027
- Roots (Multilingual): https://openreview.net/pdf?id=UoEw6KigkUn
- Red LLaMa

Expected Outcome

- Selected candidate and reason.

**Comment by ArthurMinovsky** [comment]
(Tentative) Use The pine as a English corpus for training data

**Comment by ArthurMinovsky** [comment]
To Compare with
-License
-Variety
-Used by Language Model
-Token size
-Year that data updated
