### ISSUE TITLE
Investigate which languages should be include in our experiments

### ISSUE THREAD

**Issue by new5558** [OpenThaiGPT/openthaigpt-pretraining#20]
for Some language corpus that isn't made training time longer. How many languages should be infused into the model?

**Comment by ArthurMinovsky** [comment]
Myanmar Language:
- Name Include other language
    - หาภาษาเพื่อบ้าน Myanmar
        
        ![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b6f5f7d0-9625-48b8-bd0e-2b21a1fdc540/Untitled.png)
        
        ![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/864f8134-2d2a-4d6b-bc4b-0df0ed388ba1/Untitled.png)
        
        ตัวอย่างภาษาพม่า   
        
        ['အပိုင်း ၁ သင်ခန်းစာ ၃ ကုဒ်လျှော့ရေးပါ\n',
        '“အနည်းဆုံးသုံးစွဲခြင်းဖြင့် အရာရာပြည့်စုံလုံလောက်ပါစေ” – Jules Verne\n',
        'ဒီခေတ်ကြီးမှာ ကုဒ်တွေအရမ်းများလွန်းနေတယ် ဒါဟာ ၀မ်းနည်းစရာကောင်းပေမဲ့ မှန်ကန်တဲ့အကြောင်းအချက်ပါ။\n',
        'ကျုပ်ကားအင်ဂျင်ကို ကွန်ပျူတာနဲ့ထိန်းချုပ်ထားတယ်ဆိုတဲ့အချက်ကို ကျုပ်လက်ခံနိုင်တယ်။\n',
        'မိုက်ခရိုဝေ့မီးဖိုထဲမှာ ဆော့ဝဲက ချက်တဲ့အလုပ်လုပ်တယ်ဆိုတာလည်း သိသာပါတယ်။\n']
