### ISSUE TITLE
Research Tokenization methods

### ISSUE THREAD

**Issue by new5558** [OpenThaiGPT/openthaigpt-pretraining#26]
Potential candidates:
- BPE
- BPE - Character (Sentenpiece)
- BPE (Subword MMT)
- Unigram - Character (Sentenpiece)
- Wordpiece
- Character

Description:
1. Research tokenization method to tokenize word 
2. Maybe focus on Subword

**Comment by PerasutRu** [comment]
interested !

**Comment by ArthurMinovsky** [comment]
ประเด็น limit token ในภาษาให้ chatgpt
    - cut by character (unigram, sub-word) จะไม่มีปัญหาเหมือน ****Byte-Pair Encoding****

**Comment by kwankoravich** [comment]
We decide to use unigram(sentencepiece) close by @kwankoravich
