### ISSUE TITLE
Code LIGO

### ISSUE THREAD

**Issue by new5558** [OpenThaiGPT/openthaigpt-pretraining#34]
https://techxplore.com/news/2023-03-ligo-technique-large-machine-learning.html?fbclid=IwAR3806UjbndezL666am79FzEmfy0MmXMVC-ht2A-wwe0wMeP6vdukr9BFzE
อาจารเชธฝากเปเปอร์นี้มาครับ @Model:Architecture  มีอาสาสมัครท่านไหนสนใจไปหาข้อมูลเรื่องนี้มั้ยครับ

นิวลองอ่านคร่าวๆ เค้าเอา weight ของโมเดลเล็กที่เทรนเสร็จแล้วมา transfer ให้โมเดลขนาดใหญ่ชนิดเดียวกันแต่ยังไม่ได้เทรน แล้วพอเอาไปเทรนพบว่าโมเดลใหญ่สามารถเทรนได้เสร็จเร็วขึ้นประมาณครึ่งนึง !!! 🤩 

เค้าใช้วิธีพื้นๆเลยคือ:
1. สร้าง matrix M มาทำ linear transformation weight model เล็กให้เป็น weight model ใหญ๋ ช่วยขยาย layer dimension กับ layers number
2. freeze weight model ใหญ่ ทำ SGD หา ค่า transfer ที่เหมาะสมที่สุดใน matrix M ประมาณ 100 steps
3. เลิก freeze weight model ใหญ่ แล้วเทรนโมเดลใหญ่ตามปกติเลย
แต่สิ่งที่เค้าทำหลักๆที่ทำให้ไม่เคยมีใครทำได้มาก่อน คือเค้า optimize size ของ matrix M โดยใช้เทคนิค decomposition ต่างๆ ทำให้เค้าเป็นทีมแรกๆที่ทำสำเร็จ

ข้อสังเกตุ:
- ในเปเปอร์ทดลองกับโมเดลขนาดเล็ก-กลาง (1X-3XX Million Params) โมเดลใหญ่กว่านั้นจะได้ผลเหมือนกันมั้ย
- วิธีนี้ใช้ได้กับแทบทุกโมเดล แต่ทุก layer ต้องมี dimension เท่ากัน
- optimizer ที่ทดลองเป็น SGD

สิ่งที่อยากรู้:
- จะแก้โมเดลที่มีอยู่ทุกวันนี้ให้ใช้เทคนิคนียงไง (Code)
- มขอสงเกตอนอะไรอกมยนอกจากสามขอดานบน
- ถาจะออกแบบ experiment เพอทดสอบเรองนกบ GPT ภาษาไทยทกำลงจะเทรนและมขนาดใหญกวา 1 Billion params ตองทำอะไรบาง 

https://arxiv.org/abs/2303.00980

**Comment by jingwora** [comment]
อ่านแล้ว คล้ายกับ X-MOD ที่ทีม multilingual ที่กำลังสรุปอยู่ครับ

Paper
https://aclanthology.org/2022.naacl-main.255.pdf

Pretrained Model
https://huggingface.co/docs/transformers/main/en/model_doc/xmod
