### ISSUE TITLE
Research Evaluation Dataset (Paper)

### ISSUE THREAD

**Issue by huak95** [OpenThaiGPT/openthaigpt-pretraining#37]
**We are looking for evaluation datasets in Thai and English for our NLP project.**
- We are using the LLaMA paper as an example of evaluation tasks to include.
- We will focus on six evaluation tasks, excluding mathematical reasoning and code generation:
  - Common Sense Reasoning, including BoolQ, PIQA, SIQA, HellaSwag, WinoGrande, ARC easy and challenge, and OpenBookQA.
  - Closed-book Question Answering, including Natural Questions and TraviaQA.
  - Reading Comprehension, including the RACE reading comprehension benchmark.
  - Massive Multitask Language Understanding (MMLU), consisting of multiple choice questions covering various domains of knowledge, including humanities, STEM, and social sciences.
  - The MMLU evaluation includes categories for humanities, STEM, social sciences, other, and average.
- We welcome contributions of additional evaluation datasets in Thai and English for these or other relevant NLP tasks.

**Comment by beaupranisaa** [comment]
volunteer beau

**Comment by arnajak** [comment]
volunteer arm
