### ISSUE TITLE
EDA evaluation dataset and translation

### ISSUE THREAD

**Issue by huak95** [OpenThaiGPT/openthaigpt-pretraining#40]
- We need to perform exploratory data analysis (EDA) on our NLP dataset to identify potential issues and improve our models.
- To do this, we need to create an EDA evaluation dataset consisting of a representative sample of our main dataset, including examples from all relevant languages and domains.
- The EDA dataset should be large enough to provide a meaningful sample, but small enough to be processed quickly and easily.
- We also need to create translations of our dataset in all relevant languages, either through automated translation or manual translation by native speakers.
- These translations should be high-quality and accurate, with attention paid to preserving nuances and contextual meaning.
- The translated dataset should be aligned with the original dataset, meaning that each example in the original dataset should have a corresponding translated example with the same metadata and labeling.
- We will use the EDA evaluation dataset and translations to perform thorough analysis of our main dataset, identify potential issues, and improve our models for multilingual NLP tasks.

**Comment by chawadesu** [comment]
volunteer ja
