### ISSUE TITLE
Finding pre-trained Thai LLM on Huggingfaces

### ISSUE THREAD

**Issue by huak95** [OpenThaiGPT/openthaigpt-pretraining#42]
We want to identify pre-trained Thai LLMs available on Hugging Face to use in our benchmarking evaluation.

- Searching for Thai LLMs on the Hugging Face model hub, filtering by Thai language.
- Checking for any licensing or usage restrictions for each pre-trained model to ensure that we can use them in our evaluation.

Possible Candidates:
- GPT3, GPT3.5, GPT4
- PaLM, Flan-PaLM
- OPT, LLaMA
- T5, Flan-T5
- Switch Transformers
- Chinchilla, Gopher
- GPTJ, GPTNEO-X

Multilingual models:
- Bloom, Bloomz, MT-0
- XGLM
- GLM (General Language Model, Chinese-English)

**Comment by arnajak** [comment]
volunteer kub

**Comment by huak95** [comment]
I Have Tried.

- [GPT4 ✅ (Bing) ](https://www.notion.so/GPT4-Bing-d21ca758c7b542ecb93aff05047536db)

- [GPT3.5-Turbo ✅ (ChatGPT)](https://www.notion.so/GPT3-5-Turbo-ChatGPT-747b869676f847b49e27d5928d7e8061)

- [vicuna-13b test 👻](https://www.notion.so/vicuna-13b-test-dc42590811fe4714b5d51e9dc079cd24)

- [koala-13b test ❌](https://www.notion.so/koala-13b-test-2fb7a98071464eada9826312ad0f4425)

- [alpaca-13b test ❌](https://www.notion.so/alpaca-13b-test-6e7c583e707d41f0a9d66229d99ddbe2)

- [chatglm-6b test ❌](https://www.notion.so/chatglm-6b-test-1741943acc5f44769d53c9aa6ca49ab0)

- [llama-13b test ❌](https://www.notion.so/llama-13b-test-772793b923d8466ebbf8730644a24249)

- [Flan-ul2 test ❌](https://www.notion.so/Flan-ul2-test-0b108e7b7c3b44a6b443a72a18c7bd26)

- [mGPT test 👻](https://www.notion.so/mGPT-test-3bf47977e9db4581b0c3e7d0437d4442)
