### ISSUE TITLE
EDA + Find how to clean OSCAR

### ISSUE THREAD

**Issue by Chawak** [OpenThaiGPT/openthaigpt-pretraining#46]
**Source:** https://oscar-project.github.io/documentation/versions/oscar-2019/

**Description:** EDA + Clean Thai language part of OSCAR 2019.

**Note:** You might want to sample only a few amounts of data (1%) to perform the EDA process and test your cleaning method.

**Expected Result:** 
- Python code for cleaning 
- Size and tokens comparing before/after cleaning (Use mt5 tokenizer to tokenize and count)
- (Optional) Some interesting findings from the dataset

**Interesting Papers:** 
- Study of cleaning Common Crawl to C4 https://arxiv.org/abs/2104.08758 (Note: main focus in English may not work in Thai)
- Perplexed by quality https://arxiv.org/abs/2212.10440 : Study of cleaning out harmful content use classifier and perplexity methods.

**Comment by ArthurMinovsky** [comment]
Update:
- OSCAR2019
- LDA
    - พบว่ามีภาษาจีนกับอังกฤษด้วย รวม Character พิเศษ
    - พบข้อความเหมือนใช้เหมือน google translate มา
    - เว็บโป๊ ใช้ keyword remove ด้วย แต่เว็บพนัน มันมีข่าวกีฬาด้วย (ตอนนี้กำลังหาวิธี)
- Next Steps sentence level + use classifier
