### ISSUE TITLE
Research Multilingual LM, LLM

### ISSUE THREAD

**Issue by new5558** [OpenThaiGPT/openthaigpt-pretraining#5]
- mT5 ( @kwankoravich  ) Done
- mGPT( @kwankoravich  ) Done
- XGLM (  @Ink6220  ) Done
- XMOD ( @jingwora  )
- XLM-Roberta ( @Ink6220  ) Done
- BLOOM ( @jingwora  )
- GLM ( @Ink6220  ) Done -> it should work maybe focus more the detail
- etc ( @kwankoravich @jingwora @Ink6220  ) -> mBART,...

Description:
1. Research LLM how the LLM pre-trained model with multi-language
2. Compare the techniques in each model (pros,cons)

**Comment by jingwora** [comment]
I am IN
