### ISSUE TITLE
[Super AI] Build/Modify and run Ungoliant pipeline

### ISSUE THREAD

**Issue by Chawak** [OpenThaiGPT/openthaigpt-pretraining#50]
**Objective:** We want to extract Thai data from the Common Crawl. Since OSCAR has the Ungoliant pipeline to convert common crawl to OSCAR. Modifying the pipeline to match our work (Focusing only on Thai data) might be a good idea.

**Description:** Build a pipeline to extract Thai data from the WET format of common crawl 

**Resource:**
- Original pipeline: https://github.com/oscar-project/ungoliant
- P'New version: https://github.com/new5558/ungoliant-thai
- Common Crawl Investigation: https://arxiv.org/abs/2212.10440

**Note:** The provided pipelines in the resource section are mainly written in Rust language.

**Comment by Poon2542** [comment]
Seree Yengskunpysan

**Comment by Pattptr** [comment]
สนใจขรับ

**Comment by norrawichjitaree** [comment]
สนใจครับ
