### ISSUE TITLE
[Super AI] [Good First Issue] Research on deduplicate method and impact for pretraining dataset

### ISSUE THREAD

**Issue by Chawak** [OpenThaiGPT/openthaigpt-pretraining#51]
**Description:** Research algorithms to do deduplicating the data and determine if we should do deduplication.

**Possible definitions of deduplicated data:**
- Exact match
- Near-duplicate => Only a few words different.
- Semantic duplicate => Same meaning

**Interesing papers:** 
- Dedup Google: https://arxiv.org/abs/2107.06499 (Note: this paper assumes whitespace as a tokenization technique)
- Dedup Facebook: https://arxiv.org/abs/2303.09540 (Note: this paper use fully trained LM to duplicate then train partial LM, so be aware)
- Simhash: https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/33026.pdf

**Comment by nuchhub** [comment]
สนใจค่ะ

**Comment by new5558** [comment]
Updated

Input: Huggingface Dataset
Output: Deduplicated Huggingface Dataset
