### ISSUE TITLE
Research which library to supports

### ISSUE THREAD

**Issue by new5558** [OpenThaiGPT/openthaigpt-pretraining#7]
Candidates library
- Huggingface (A must)
- Simpletransformer
- Sentencetransformers
- TRLX
- PEFT
- TBD

**Comment by bryanwongma** [comment]
Cheers!

**Comment by peeraponw** [comment]
Hey all,

As far as I understood, our pretrained model falls into Text Generation task. I have explored PyThaiNLP source code and found that there exists `pythainlp.generate` module in which the implemented models are only N-gram family. Those N-gram models derive from static text corpi which are downloaded from their Github repo. We can potentially contribute our implementation of (maybe) GPT family models, or our custom models to this module.

With this strategy, I assume that saving `pytorch_model.bin` and/or `model.safetensors` in HuggingFace repo and call:

```
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("OpenThaiGPT-v1") # dummy name

model = AutoModelForCausalLM.from_pretrained("OpenThaiGPT-v1")
```

inside our model class in `pythainlp.generate` would be sufficient. Please let me know if there are any concerns that I overlooked/misunderstood.
