### ISSUE TITLE
Experiment tokenization method to LLaMa

### ISSUE THREAD

**Issue by kwankoravich** [OpenThaiGPT/openthaigpt-pretraining#85]
Super AI Tasks or Volunteer

Tokenization methods:

BPE
BPE - Character (Sentenpiece)
BPE (Subword MMT)
Unigram - Character (Sentenpiece) 
Wordpiece
Character

**Comment by jingwora** [comment]
I will do this task.

**Comment by jingwora** [comment]
https://colab.research.google.com/drive/195fDdYA-dfMYIRPbPEv3VvaJ-_cD5SKD?usp=sharing#scrollTo=48zVmpQBqwra
