### ISSUE TITLE
[Super AI] Model deploy to Huggingface [1MD]

### ISSUE THREAD

**Issue by bryanwongma** [OpenThaiGPT/openthaigpt-pretraining#92]

**Comment by bryanwongma** [comment]
Please review and document https://colab.research.google.com/drive/1Ph7D3tFfYy_WKJ35nPscR6U6OlPFnl0h

**Comment by srn-source** [comment]
> Please review and document https://colab.research.google.com/drive/1Ph7D3tFfYy_WKJ35nPscR6U6OlPFnl0h

@bryanwongma  คนจากทีมโมเดลเข้าดูได้ไหมครับ เหมือน colab จะเข้าไม่ได้ครับ

**Comment by bryanwongma** [comment]
@srn-source ฝากเช็คอีกทีครับปรับเป็นทุกคนที่มีลิ้งสามารถดูได้แล้วครับ

Fine-tune Model
https://colab.research.google.com/drive/18qxm3gDdTobpuIvyUDa5RSSNBI7Ey7sR?usp=sharing

**Deploy Model** edit permission
https://colab.research.google.com/drive/1Ph7D3tFfYy_WKJ35nPscR6U6OlPFnl0h?usp=sharing

**Comment by srn-source** [comment]
> @srn-source ฝากเช็คอีกทีครับปรับเป็นทุกคนที่มีลิ้งสามารถดูได้แล้วครับ
> 
> Fine-tune Model https://colab.research.google.com/drive/18qxm3gDdTobpuIvyUDa5RSSNBI7Ey7sR?usp=sharing
> 
> **Deploy Model** edit permission https://colab.research.google.com/drive/1Ph7D3tFfYy_WKJ35nPscR6U6OlPFnl0h?usp=sharing

ทั้งสองลิ้ง สามารถเข้าได้ปกติแล้วครับ ขอบคุณครับ
